#!/usr/bin/env bash

# 2014-12-17 08:58:02.0 +0100 / Gilles Quenot <gilles.quenot@sputnick.fr>

# This wrapper script is aimed to query XML files
# like XMLStarlet or xmllint, but with the ability to use XPath 3.

# Need to be edited, the PATH to saxon9he.jar
saxonPATH="/usr/share/java/saxon"

# -----8<--------------- code now:
jar="$saxonPATH/saxon9he.jar"
class=net.sf.saxon.Query

if [[ ! -s $jar ]]; then
    echo >&2 "ERROR:The variable saxonPATH in $0 should be edited with the PATH to saxon9he.jar"
    exit 1
fi

if [[ ! $@ || $1 == -h || $1 == --help ]]; then
    cat<<EOF >&2
Usage:
    ${0##*/} <QUERY> [<file> | <files*>]
EOF
    exit 1
fi

query="$1"
shift

if [[ -s $1 ]]; then
    files=( "$@" )
else
    files=( - ) # STDIN
fi

for file in "${files[@]}"; do
    java -cp "$jar" "$class" -s:"$file" -qs:"$query" !method=text !item-separator=$'\n'
done
